coverage:
  status:
    project:
      default:
        flags:
          - angular
    patch:
      default:
        flags:
          - angular

flags:
  angular:
    paths:
      - src/app/
    carryforward: true
